config/routes.rb
Rails.application.routes.draw do
  root "dashboard#index"
  resources :admins
  resources :ads
  resources :ad_views
  resources :animals
  resources :avatars
  resources :breeds
  resources :chats
  resources :dislikes
  resources :likes
  resources :messages
  resources :user_notifications
  resources :quota
  resources :user_reports
  resources :subscriptions
  resources :tiers
  resources :transactions
  resources :types
  resources :users

  namespace :api do
    namespace :v1 do
      resources :registrations, only: %i[create update] do
        collection do
          put 'verify_otp'
          put 'resend_otp'
          put 'create_profile'
        end
      end
      resources :sessions, only: %i[create destroy]
      resources :users, only: %i[show update destroy] do
        collection do
          get 'show_other'
        end
      end
      resources :animals, except: %i[index edit] do
        collection do
          put 'edit_avatar'
        end
      end
      resources :recommendations, only: %i[index]
      resources :likes, only: %i[create]
      resources :dislikes, only: %i[create]
      resources :user_notifications, only: %i[index]
      resources :chats, only: %i[index show update] do
        collection do
          get 'blocked_users'
        end
      end
      resources :messages, only: %i[index create] #index for unread messages
      resources :subscriptions, only: %i[show]
      resources :user_reports, only: %i[create]
      resources :tiers, only: %i[index]
      resources :transactions, only: %i[create]
      resources :paymob_transactions, only: %i[create]
      resources :ads, only: %i[index update]
      resources :ads, only: %i[index]
    end
  end
end

app/models/breed.rb
class Breed < ApplicationRecord
    has_many :animals, -> { order(id: :asc) }
    belongs_to :type
end

app/controllers/breeds_controller.rb
class BreedsController < ApplicationController
  before_action :set_breed, only: %i[ show edit update destroy ]

  # GET /breeds or /breeds.json
  def index
    @breeds = Breed.all
  end

  # GET /breeds/1 or /breeds/1.json
  def show
  end

  # GET /breeds/new
  def new
    @breed = Breed.new
  end

  # GET /breeds/1/edit
  def edit
  end

  # POST /breeds or /breeds.json
  def create
    @breed = Breed.new(breed_params)

    respond_to do |format|
      if @breed.save
        format.html { redirect_to breed_url(@breed), notice: "Breed was successfully created." }
        format.json { render :show, status: :created, location: @breed }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @breed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /breeds/1 or /breeds/1.json
  def update
    respond_to do |format|
      if @breed.update(breed_params)
        format.html { redirect_to breed_url(@breed), notice: "Breed was successfully updated." }
        format.json { render :show, status: :ok, location: @breed }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @breed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /breeds/1 or /breeds/1.json
  def destroy
    @breed.destroy

    respond_to do |format|
      format.html { redirect_to breeds_url, notice: "Breed was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_breed
      @breed = Breed.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def breed_params
      params.require(:breed).permit(:name, :type_id)
    end
end

app/views/breeds/_breed.html.erb
<div id="<%= dom_id breed %>">
  <p>
    <strong>Name:</strong>
    <%= breed.name %>
  </p>

  <p>
    <strong>Type:</strong>
    <%= breed.type_id %>
  </p>

</div>

app/views/breeds/_form.html.erb
<%= form_with(model: breed) do |form| %>
  <% if breed.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(breed.errors.count, "error") %> prohibited this breed from being saved:</h2>

      <ul>
        <% breed.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :type_id, style: "display: block" %>
    <%= form.number_field :type_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/breeds/edit.html.erb
<h1>Editing breed</h1>

<%= render "form", breed: @breed %>

<br>

<div>
  <%= link_to "Show this breed", @breed %> |
  <%= link_to "Back to breeds", breeds_path %>
</div>

app/views/breeds/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Breeds</h1>

<div id="breeds">
  <% @breeds.each do |breed| %>
    <%= render breed %>
    <p>
      <%= link_to "Show this breed", breed %>
    </p>
  <% end %>
</div>

<%= link_to "New breed", new_breed_path %>

app/views/breeds/new.html.erb
<h1>New breed</h1>

<%= render "form", breed: @breed %>

<br>

<div>
  <%= link_to "Back to breeds", breeds_path %>
</div>

app/views/breeds/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @breed %>

<div>
  <%= link_to "Edit this breed", edit_breed_path(@breed) %> |
  <%= link_to "Back to breeds", breeds_path %>

  <%= button_to "Destroy this breed", @breed, method: :delete %>
</div>