config/routes.rb
Rails.application.routes.draw do
  root "dashboard#index"
  resources :admins
  resources :ads
  resources :ad_views
  resources :animals
  resources :avatars
  resources :breeds
  resources :chats
  resources :dislikes
  resources :likes
  resources :messages
  resources :user_notifications
  resources :quota
  resources :user_reports
  resources :subscriptions
  resources :tiers
  resources :transactions
  resources :types
  resources :users

  namespace :api do
    namespace :v1 do
      resources :registrations, only: %i[create update] do
        collection do
          put 'verify_otp'
          put 'resend_otp'
          put 'create_profile'
        end
      end
      resources :sessions, only: %i[create destroy]
      resources :users, only: %i[show update destroy] do
        collection do
          get 'show_other'
        end
      end
      resources :animals, except: %i[index edit] do
        collection do
          put 'edit_avatar'
        end
      end
      resources :recommendations, only: %i[index]
      resources :likes, only: %i[create]
      resources :dislikes, only: %i[create]
      resources :user_notifications, only: %i[index]
      resources :chats, only: %i[index show update] do
        collection do
          get 'blocked_users'
        end
      end
      resources :messages, only: %i[index create] #index for unread messages
      resources :subscriptions, only: %i[show]
      resources :user_reports, only: %i[create]
      resources :tiers, only: %i[index]
      resources :transactions, only: %i[create]
      resources :paymob_transactions, only: %i[create]
      resources :ads, only: %i[index update]
      resources :ads, only: %i[index]
    end
  end
end

app/models/animal.rb
class Animal < ApplicationRecord
    reverse_geocoded_by :latitude, :longitude
    belongs_to :user
    belongs_to :breed
    has_one :type, through: :breed
    has_many :avatars
    has_many :likes, foreign_key: "liked_animal_id", counter_cache: true         # Likes made to him
    has_many :dislikes, foreign_key: "disliker_animal_id"   # Dislikes he made

    def likes_count
        likes.count
    end

    def recommendations(params)
        animals_to_exclude_ids = dislikes.pluck(:disliked_animal_id) +
                                    Like.where(liker_animal_id: id).pluck(:liked_animal_id) +
                                    Like.where(liked_animal_id: id, is_liked_back: true).pluck(:liker_animal_id) +
                                    user.animals.pluck(:id)
        
        min_dob = DateTime.now - params[:max_age].to_i.years
        max_dob = DateTime.now - params[:min_age].to_i.years

        recs = params[:same_breed] ? breed.animals : type.animals
        recs =  recs.where.not(gender: gender)
                    .where("dob >= ?", min_dob)
                    .where("dob <= ?", max_dob)
                    .where.not(id: animals_to_exclude_ids)

        recs = recs.where(vaccinated: true) unless params[:no_vaccination_needed]
        recs = recs.near([latitude, longitude], params[:distance], units: :km) if params[:distance].to_i != 0
        recs.limit(10)
    end
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  before_action :set_animal, only: %i[ show edit update destroy ]
  # with('avatars', 'user') inculde

  # GET /animals or /animals.json
  def index
    @animals = Animal.all
  end

  # GET /animals/1 or /animals/1.json
  def show
    
  end

  # GET /animals/new
  def new
    @animal = Animal.new
  end

  # GET /animals/1/edit
  def edit
  end

  # POST /animals or /animals.json
  def create
    @animal = Animal.new(animal_params)

    respond_to do |format|
      if @animal.save
        format.html { redirect_to animal_url(@animal), notice: "Animal was successfully created." }
        format.json { render :show, status: :created, location: @animal }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /animals/1 or /animals/1.json
  def update
    respond_to do |format|
      if @animal.update(animal_params)
        format.html { redirect_to animal_url(@animal), notice: "Animal was successfully updated." }
        format.json { render :show, status: :ok, location: @animal }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /animals/1 or /animals/1.json
  def destroy
    @animal.destroy

    respond_to do |format|
      format.html { redirect_to animals_url, notice: "Animal was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_animal
      @animal = Animal.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def animal_params
      params.require(:animal).permit(:user_id, :breed_id, :name, :gender, :bio, :dob, :vaccinated, :longitude, :latitude)
    end
end

app/controllers/api/v1/animals_controller.rb
class Api::V1::AnimalsController < Api::V1::ApiController
  before_action :set_animal, only: %i[ show edit update destroy ]
  # with('avatars', 'user') inculde

  # GET /animals/1 or /animals/1.json
  def show
    render json: @animal, include: [:type, :breed, :avatars, :user], methods: :likes_count
  end


  def new
    render json: Type.all, include: :breeds
  end
  

  # GET /animals/edit_avatar
  def edit_avatar
    # @animal = Animal.new
  end

  # POST /animals or /animals.json
  def create
    @animal = @current_user.animals.build(name: params[:name], bio: params[:bio], gender: params[:gender], breed_id: params[:breed_id], vaccinated: params[:vaccinated])
    @animal.dob = params[:dob]
    @animal.longitude = @current_user.longitude
    @animal.latitude = @current_user.latitude
    avatar = Cloudinary::Uploader.upload(params[:avatar], use_filename:true, unique_filename:true, overwrite:true)
      if @animal.save
        @animal.avatars.build(url: avatar['secure_url'], caption: params[:bio]).save
        render json: {message: 'created', animal_id: @animal.id}
      else
        render json: :failed
      end
  end

  # PATCH/PUT /animals/1 or /animals/1.json
  def update
      if @animal.update(name: params[:name], bio: params[:bio], vaccinated: params[:vaccinated])
        render json: :updated
      else
        render json: :failed
      end
  end

  # DELETE /animals/1 or /animals/1.json
  def destroy
    @animal.destroy

    render json: :deleted
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_animal
      @animal = Animal.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def animal_params
      params.require(:animal).permit(:user_id, :breed_id, :name, :gender, :bio, :dob, :vaccinated, :longitude, :latitude)
    end
end

app/views/animals/_animal.html.erb
<div id="<%= dom_id animal %>">
  <p>
    <strong>User:</strong>
    <%= animal.user_id %>
  </p>

  <p>
    <strong>Breed:</strong>
    <%= animal.breed_id %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= animal.name %>
  </p>

  <p>
    <strong>Gender:</strong>
    <%= animal.gender %>
  </p>

  <p>
    <strong>Bio:</strong>
    <%= animal.bio %>
  </p>

  <p>
    <strong>Dob:</strong>
    <%= animal.dob %>
  </p>

  <p>
    <strong>Vaccinated:</strong>
    <%= animal.vaccinated %>
  </p>

  <p>
    <strong>Longitude:</strong>
    <%= animal.longitude %>
  </p>

  <p>
    <strong>Latitude:</strong>
    <%= animal.latitude %>
  </p>

</div>

app/views/animals/_form.html.erb
<%= form_with(model: animal) do |form| %>
  <% if animal.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(animal.errors.count, "error") %> prohibited this animal from being saved:</h2>

      <ul>
        <% animal.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.number_field :user_id %>
  </div>

  <div>
    <%= form.label :breed_id, style: "display: block" %>
    <%= form.number_field :breed_id %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :gender, style: "display: block" %>
    <%= form.text_field :gender %>
  </div>

  <div>
    <%= form.label :bio, style: "display: block" %>
    <%= form.text_area :bio %>
  </div>

  <div>
    <%= form.label :dob, style: "display: block" %>
    <%= form.datetime_field :dob %>
  </div>

  <div>
    <%= form.label :vaccinated, style: "display: block" %>
    <%= form.check_box :vaccinated %>
  </div>

  <div>
    <%= form.label :longitude, style: "display: block" %>
    <%= form.text_field :longitude %>
  </div>

  <div>
    <%= form.label :latitude, style: "display: block" %>
    <%= form.text_field :latitude %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/animals/edit.html.erb
<h1>Editing animal</h1>

<%= render "form", animal: @animal %>

<br>

<div>
  <%= link_to "Show this animal", @animal %> |
  <%= link_to "Back to animals", animals_path %>
</div>

app/views/animals/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Animals</h1>

<div id="animals">
  <% @animals.each do |animal| %>
    <%= render animal %>
    <p>
      <%= link_to "Show this animal", animal %>
    </p>
  <% end %>
</div>

<%= link_to "New animal", new_animal_path %>

app/views/animals/new.html.erb
<h1>New animal</h1>

<%= render "form", animal: @animal %>

<br>

<div>
  <%= link_to "Back to animals", animals_path %>
</div>

app/views/animals/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @animal %>

<div>
  <%= link_to "Edit this animal", edit_animal_path(@animal) %> |
  <%= link_to "Back to animals", animals_path %>

  <%= button_to "Destroy this animal", @animal, method: :delete %>
</div>