config/routes.rb
Rails.application.routes.draw do
  root "dashboard#index"
  resources :admins
  resources :ads
  resources :ad_views
  resources :animals
  resources :avatars
  resources :breeds
  resources :chats
  resources :dislikes
  resources :likes
  resources :messages
  resources :user_notifications
  resources :quota
  resources :user_reports
  resources :subscriptions
  resources :tiers
  resources :transactions
  resources :types
  resources :users

  namespace :api do
    namespace :v1 do
      resources :registrations, only: %i[create update] do
        collection do
          put 'verify_otp'
          put 'resend_otp'
          put 'create_profile'
        end
      end
      resources :sessions, only: %i[create destroy]
      resources :users, only: %i[show update destroy] do
        collection do
          get 'show_other'
        end
      end
      resources :animals, except: %i[index edit] do
        collection do
          put 'edit_avatar'
        end
      end
      resources :recommendations, only: %i[index]
      resources :likes, only: %i[create]
      resources :dislikes, only: %i[create]
      resources :user_notifications, only: %i[index]
      resources :chats, only: %i[index show update] do
        collection do
          get 'blocked_users'
        end
      end
      resources :messages, only: %i[index create] #index for unread messages
      resources :subscriptions, only: %i[show]
      resources :user_reports, only: %i[create]
      resources :tiers, only: %i[index]
      resources :transactions, only: %i[create]
      resources :paymob_transactions, only: %i[create]
      resources :ads, only: %i[index update]
      resources :ads, only: %i[index]
    end
  end
end

app/models/subscription.rb
class Subscription < ApplicationRecord
    belongs_to :tier
    belongs_to :user
end

app/controllers/api/v1/subscriptions_controller.rb
class Api::V1::SubscriptionsController < Api::V1::ApiController
  def show
    render json: @current_user.subscription
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :set_subscription, only: %i[ show edit update destroy ]

  # GET /subscriptions or /subscriptions.json
  def index
    @subscriptions = Subscription.all
  end

  # GET /subscriptions/1 or /subscriptions/1.json
  def show
  end

  # GET /subscriptions/new
  def new
    @subscription = Subscription.new
  end

  # GET /subscriptions/1/edit
  def edit
  end

  # POST /subscriptions or /subscriptions.json
  def create
    @subscription = Subscription.new(subscription_params)

    respond_to do |format|
      if @subscription.save
        format.html { redirect_to subscription_url(@subscription), notice: "Subscription was successfully created." }
        format.json { render :show, status: :created, location: @subscription }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subscriptions/1 or /subscriptions/1.json
  def update
    respond_to do |format|
      if @subscription.update(subscription_params)
        format.html { redirect_to subscription_url(@subscription), notice: "Subscription was successfully updated." }
        format.json { render :show, status: :ok, location: @subscription }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscriptions/1 or /subscriptions/1.json
  def destroy
    @subscription.destroy

    respond_to do |format|
      format.html { redirect_to subscriptions_url, notice: "Subscription was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscription
      @subscription = Subscription.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def subscription_params
      params.require(:subscription).permit(:user_id, :tier_id, :has_unlimited_likes, :likes, :max_file_size, :pets, :ads)
    end
end

app/helpers/api/v1/subscriptions_helper.rb
module Api::V1::SubscriptionsHelper
end

app/views/subscriptions/_form.html.erb
<%= form_with(model: subscription) do |form| %>
  <% if subscription.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(subscription.errors.count, "error") %> prohibited this subscription from being saved:</h2>

      <ul>
        <% subscription.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.number_field :user_id %>
  </div>

  <div>
    <%= form.label :tier_id, style: "display: block" %>
    <%= form.number_field :tier_id %>
  </div>

  <div>
    <%= form.label :has_unlimited_likes, style: "display: block" %>
    <%= form.check_box :has_unlimited_likes %>
  </div>

  <div>
    <%= form.label :likes, style: "display: block" %>
    <%= form.number_field :likes %>
  </div>

  <div>
    <%= form.label :max_file_size, style: "display: block" %>
    <%= form.number_field :max_file_size %>
  </div>

  <div>
    <%= form.label :pets, style: "display: block" %>
    <%= form.number_field :pets %>
  </div>

  <div>
    <%= form.label :ads, style: "display: block" %>
    <%= form.check_box :ads %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/subscriptions/_subscription.html.erb
<div id="<%= dom_id subscription %>">
  <p>
    <strong>User:</strong>
    <%= subscription.user_id %>
  </p>

  <p>
    <strong>Tier:</strong>
    <%= subscription.tier_id %>
  </p>

  <p>
    <strong>Has unlimited likes:</strong>
    <%= subscription.has_unlimited_likes %>
  </p>

  <p>
    <strong>Likes:</strong>
    <%= subscription.likes %>
  </p>

  <p>
    <strong>Max file size:</strong>
    <%= subscription.max_file_size %>
  </p>

  <p>
    <strong>Pets:</strong>
    <%= subscription.pets %>
  </p>

  <p>
    <strong>Ads:</strong>
    <%= subscription.ads %>
  </p>

</div>

app/views/subscriptions/edit.html.erb
<h1>Editing subscription</h1>

<%= render "form", subscription: @subscription %>

<br>

<div>
  <%= link_to "Show this subscription", @subscription %> |
  <%= link_to "Back to subscriptions", subscriptions_path %>
</div>

app/views/subscriptions/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Subscriptions</h1>

<div id="subscriptions">
  <% @subscriptions.each do |subscription| %>
    <%= render subscription %>
    <p>
      <%= link_to "Show this subscription", subscription %>
    </p>
  <% end %>
</div>

<%= link_to "New subscription", new_subscription_path %>

app/views/subscriptions/new.html.erb
<h1>New subscription</h1>

<%= render "form", subscription: @subscription %>

<br>

<div>
  <%= link_to "Back to subscriptions", subscriptions_path %>
</div>

app/views/subscriptions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @subscription %>

<div>
  <%= link_to "Edit this subscription", edit_subscription_path(@subscription) %> |
  <%= link_to "Back to subscriptions", subscriptions_path %>

  <%= button_to "Destroy this subscription", @subscription, method: :delete %>
</div>